/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CelebrationRouteImport } from './routes/$celebration'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAtelierRouteImport } from './routes/_authenticated/atelier'
import { Route as AuthenticatedConfirmRouteImport } from './routes/_authenticated/confirm'
import { Route as AuthenticatedDeliveryRouteImport } from './routes/_authenticated/delivery'
import { Route as AuthenticatedEventRouteImport } from './routes/_authenticated/event'
import { Route as AuthenticatedGuestsRouteImport } from './routes/_authenticated/guests'
import { Route as AuthenticatedHostsRouteImport } from './routes/_authenticated/hosts'
import { Route as AuthenticatedInvitationRouteImport } from './routes/_authenticated/invitation'
import { Route as AuthenticatedInviteRouteImport } from './routes/_authenticated/invite'
import { Route as AuthenticatedLookbookRouteImport } from './routes/_authenticated/lookbook'
import { Route as AuthenticatedMeasurementsRouteImport } from './routes/_authenticated/measurements'
import { Route as AuthenticatedOutfitsRouteImport } from './routes/_authenticated/outfits'
import { Route as AuthenticatedPayRouteImport } from './routes/_authenticated/pay'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedSummaryRouteImport } from './routes/_authenticated/summary'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated/upgrade'
import { Route as AuthenticatedFamilyHouseholdRouteImport } from './routes/_authenticated/family.$household'
import { Route as AuthenticatedGuestGuestIdRouteImport } from './routes/_authenticated/guest.$guestId'
import { Route as AuthenticatedGuestInviteRouteImport } from './routes/_authenticated/guest.invite'
import { Route as AuthenticatedGuestMeasurementsRouteImport } from './routes/_authenticated/guest.measurements'
import { Route as AuthenticatedGuestOutfitsRouteImport } from './routes/_authenticated/guest.outfits'
import { Route as AuthenticatedGuestScheduleRouteImport } from './routes/_authenticated/guest.schedule'
import { Route as AuthenticatedGuestSummaryRouteImport } from './routes/_authenticated/guest.summary'
import { Route as AuthenticatedHostIndexRouteImport } from './routes/_authenticated/host.index'
import { Route as AuthenticatedHostSplatRouteImport } from './routes/_authenticated/host.$'
import { Route as ApiPublicFollowupRemindersRouteImport } from './routes/api/public/followup-reminders'
import { Route as ApiPublicOutfitImportWorkerRouteImport } from './routes/api/public/outfit-import-worker'
import { Route as LovableEmailEventsRouteImport } from './routes/lovable/email/events'
import { Route as ApiPublicEmailInboundRouteImport } from './routes/api/public/email/inbound'
import { Route as ApiPublicOutfitImageSplatRouteImport } from './routes/api/public/outfit-image.$'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebrationRoute = CelebrationRouteImport.update({
  id: '/$celebration',
  path: '/$celebration',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtelierRoute = AuthenticatedAtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfirmRoute = AuthenticatedConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliveryRoute = AuthenticatedDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventRoute = AuthenticatedEventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuestsRoute = AuthenticatedGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHostsRoute = AuthenticatedHostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitationRoute = AuthenticatedInvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInviteRoute = AuthenticatedInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLookbookRoute = AuthenticatedLookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeasurementsRoute =
  AuthenticatedMeasurementsRouteImport.update({
    id: '/measurements',
    path: '/measurements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutfitsRoute = AuthenticatedOutfitsRouteImport.update({
  id: '/outfits',
  path: '/outfits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayRoute = AuthenticatedPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSummaryRoute = AuthenticatedSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilyHouseholdRoute =
  AuthenticatedFamilyHouseholdRouteImport.update({
    id: '/family/$household',
    path: '/family/$household',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuestGuestIdRoute =
  AuthenticatedGuestGuestIdRouteImport.update({
    id: '/guest/$guestId',
    path: '/guest/$guestId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuestInviteRoute =
  AuthenticatedGuestInviteRouteImport.update({
    id: '/guest/invite',
    path: '/guest/invite',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuestMeasurementsRoute =
  AuthenticatedGuestMeasurementsRouteImport.update({
    id: '/guest/measurements',
    path: '/guest/measurements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuestOutfitsRoute =
  AuthenticatedGuestOutfitsRouteImport.update({
    id: '/guest/outfits',
    path: '/guest/outfits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuestScheduleRoute =
  AuthenticatedGuestScheduleRouteImport.update({
    id: '/guest/schedule',
    path: '/guest/schedule',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuestSummaryRoute =
  AuthenticatedGuestSummaryRouteImport.update({
    id: '/guest/summary',
    path: '/guest/summary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHostIndexRoute = AuthenticatedHostIndexRouteImport.update({
  id: '/host/',
  path: '/host/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHostSplatRoute = AuthenticatedHostSplatRouteImport.update({
  id: '/host/$',
  path: '/host/$',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicFollowupRemindersRoute =
  ApiPublicFollowupRemindersRouteImport.update({
    id: '/api/public/followup-reminders',
    path: '/api/public/followup-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOutfitImportWorkerRoute =
  ApiPublicOutfitImportWorkerRouteImport.update({
    id: '/api/public/outfit-import-worker',
    path: '/api/public/outfit-import-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailEventsRoute = LovableEmailEventsRouteImport.update({
  id: '/lovable/email/events',
  path: '/lovable/email/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailInboundRoute = ApiPublicEmailInboundRouteImport.update({
  id: '/api/public/email/inbound',
  path: '/api/public/email/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOutfitImageSplatRoute =
  ApiPublicOutfitImageSplatRouteImport.update({
    id: '/api/public/outfit-image/$',
    path: '/api/public/outfit-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$celebration': typeof CelebrationRoute
  '/auth': typeof AuthRoute
  '/atelier': typeof AuthenticatedAtelierRoute
  '/confirm': typeof AuthenticatedConfirmRoute
  '/delivery': typeof AuthenticatedDeliveryRoute
  '/event': typeof AuthenticatedEventRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/hosts': typeof AuthenticatedHostsRoute
  '/invitation': typeof AuthenticatedInvitationRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/lookbook': typeof AuthenticatedLookbookRoute
  '/measurements': typeof AuthenticatedMeasurementsRoute
  '/outfits': typeof AuthenticatedOutfitsRoute
  '/pay': typeof AuthenticatedPayRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/summary': typeof AuthenticatedSummaryRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/family/$household': typeof AuthenticatedFamilyHouseholdRoute
  '/guest/$guestId': typeof AuthenticatedGuestGuestIdRoute
  '/guest/invite': typeof AuthenticatedGuestInviteRoute
  '/guest/measurements': typeof AuthenticatedGuestMeasurementsRoute
  '/guest/outfits': typeof AuthenticatedGuestOutfitsRoute
  '/guest/schedule': typeof AuthenticatedGuestScheduleRoute
  '/guest/summary': typeof AuthenticatedGuestSummaryRoute
  '/host/$': typeof AuthenticatedHostSplatRoute
  '/api/public/followup-reminders': typeof ApiPublicFollowupRemindersRoute
  '/api/public/outfit-import-worker': typeof ApiPublicOutfitImportWorkerRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/host/': typeof AuthenticatedHostIndexRoute
  '/api/public/email/inbound': typeof ApiPublicEmailInboundRoute
  '/api/public/outfit-image/$': typeof ApiPublicOutfitImageSplatRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$celebration': typeof CelebrationRoute
  '/auth': typeof AuthRoute
  '/atelier': typeof AuthenticatedAtelierRoute
  '/confirm': typeof AuthenticatedConfirmRoute
  '/delivery': typeof AuthenticatedDeliveryRoute
  '/event': typeof AuthenticatedEventRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/hosts': typeof AuthenticatedHostsRoute
  '/invitation': typeof AuthenticatedInvitationRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/lookbook': typeof AuthenticatedLookbookRoute
  '/measurements': typeof AuthenticatedMeasurementsRoute
  '/outfits': typeof AuthenticatedOutfitsRoute
  '/pay': typeof AuthenticatedPayRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/summary': typeof AuthenticatedSummaryRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/family/$household': typeof AuthenticatedFamilyHouseholdRoute
  '/guest/$guestId': typeof AuthenticatedGuestGuestIdRoute
  '/guest/invite': typeof AuthenticatedGuestInviteRoute
  '/guest/measurements': typeof AuthenticatedGuestMeasurementsRoute
  '/guest/outfits': typeof AuthenticatedGuestOutfitsRoute
  '/guest/schedule': typeof AuthenticatedGuestScheduleRoute
  '/guest/summary': typeof AuthenticatedGuestSummaryRoute
  '/host/$': typeof AuthenticatedHostSplatRoute
  '/api/public/followup-reminders': typeof ApiPublicFollowupRemindersRoute
  '/api/public/outfit-import-worker': typeof ApiPublicOutfitImportWorkerRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/host': typeof AuthenticatedHostIndexRoute
  '/api/public/email/inbound': typeof ApiPublicEmailInboundRoute
  '/api/public/outfit-image/$': typeof ApiPublicOutfitImageSplatRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$celebration': typeof CelebrationRoute
  '/auth': typeof AuthRoute
  '/_authenticated/atelier': typeof AuthenticatedAtelierRoute
  '/_authenticated/confirm': typeof AuthenticatedConfirmRoute
  '/_authenticated/delivery': typeof AuthenticatedDeliveryRoute
  '/_authenticated/event': typeof AuthenticatedEventRoute
  '/_authenticated/guests': typeof AuthenticatedGuestsRoute
  '/_authenticated/hosts': typeof AuthenticatedHostsRoute
  '/_authenticated/invitation': typeof AuthenticatedInvitationRoute
  '/_authenticated/invite': typeof AuthenticatedInviteRoute
  '/_authenticated/lookbook': typeof AuthenticatedLookbookRoute
  '/_authenticated/measurements': typeof AuthenticatedMeasurementsRoute
  '/_authenticated/outfits': typeof AuthenticatedOutfitsRoute
  '/_authenticated/pay': typeof AuthenticatedPayRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/summary': typeof AuthenticatedSummaryRoute
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/_authenticated/family/$household': typeof AuthenticatedFamilyHouseholdRoute
  '/_authenticated/guest/$guestId': typeof AuthenticatedGuestGuestIdRoute
  '/_authenticated/guest/invite': typeof AuthenticatedGuestInviteRoute
  '/_authenticated/guest/measurements': typeof AuthenticatedGuestMeasurementsRoute
  '/_authenticated/guest/outfits': typeof AuthenticatedGuestOutfitsRoute
  '/_authenticated/guest/schedule': typeof AuthenticatedGuestScheduleRoute
  '/_authenticated/guest/summary': typeof AuthenticatedGuestSummaryRoute
  '/_authenticated/host/$': typeof AuthenticatedHostSplatRoute
  '/api/public/followup-reminders': typeof ApiPublicFollowupRemindersRoute
  '/api/public/outfit-import-worker': typeof ApiPublicOutfitImportWorkerRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/_authenticated/host/': typeof AuthenticatedHostIndexRoute
  '/api/public/email/inbound': typeof ApiPublicEmailInboundRoute
  '/api/public/outfit-image/$': typeof ApiPublicOutfitImageSplatRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$celebration'
    | '/auth'
    | '/atelier'
    | '/confirm'
    | '/delivery'
    | '/event'
    | '/guests'
    | '/hosts'
    | '/invitation'
    | '/invite'
    | '/lookbook'
    | '/measurements'
    | '/outfits'
    | '/pay'
    | '/plan'
    | '/platform'
    | '/portal'
    | '/schedule'
    | '/summary'
    | '/upgrade'
    | '/family/$household'
    | '/guest/$guestId'
    | '/guest/invite'
    | '/guest/measurements'
    | '/guest/outfits'
    | '/guest/schedule'
    | '/guest/summary'
    | '/host/$'
    | '/api/public/followup-reminders'
    | '/api/public/outfit-import-worker'
    | '/lovable/email/events'
    | '/host/'
    | '/api/public/email/inbound'
    | '/api/public/outfit-image/$'
    | '/api/public/whatsapp/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$celebration'
    | '/auth'
    | '/atelier'
    | '/confirm'
    | '/delivery'
    | '/event'
    | '/guests'
    | '/hosts'
    | '/invitation'
    | '/invite'
    | '/lookbook'
    | '/measurements'
    | '/outfits'
    | '/pay'
    | '/plan'
    | '/platform'
    | '/portal'
    | '/schedule'
    | '/summary'
    | '/upgrade'
    | '/family/$household'
    | '/guest/$guestId'
    | '/guest/invite'
    | '/guest/measurements'
    | '/guest/outfits'
    | '/guest/schedule'
    | '/guest/summary'
    | '/host/$'
    | '/api/public/followup-reminders'
    | '/api/public/outfit-import-worker'
    | '/lovable/email/events'
    | '/host'
    | '/api/public/email/inbound'
    | '/api/public/outfit-image/$'
    | '/api/public/whatsapp/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$celebration'
    | '/auth'
    | '/_authenticated/atelier'
    | '/_authenticated/confirm'
    | '/_authenticated/delivery'
    | '/_authenticated/event'
    | '/_authenticated/guests'
    | '/_authenticated/hosts'
    | '/_authenticated/invitation'
    | '/_authenticated/invite'
    | '/_authenticated/lookbook'
    | '/_authenticated/measurements'
    | '/_authenticated/outfits'
    | '/_authenticated/pay'
    | '/_authenticated/plan'
    | '/_authenticated/platform'
    | '/_authenticated/portal'
    | '/_authenticated/schedule'
    | '/_authenticated/summary'
    | '/_authenticated/upgrade'
    | '/_authenticated/family/$household'
    | '/_authenticated/guest/$guestId'
    | '/_authenticated/guest/invite'
    | '/_authenticated/guest/measurements'
    | '/_authenticated/guest/outfits'
    | '/_authenticated/guest/schedule'
    | '/_authenticated/guest/summary'
    | '/_authenticated/host/$'
    | '/api/public/followup-reminders'
    | '/api/public/outfit-import-worker'
    | '/lovable/email/events'
    | '/_authenticated/host/'
    | '/api/public/email/inbound'
    | '/api/public/outfit-image/$'
    | '/api/public/whatsapp/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CelebrationRoute: typeof CelebrationRoute
  AuthRoute: typeof AuthRoute
  ApiPublicFollowupRemindersRoute: typeof ApiPublicFollowupRemindersRoute
  ApiPublicOutfitImportWorkerRoute: typeof ApiPublicOutfitImportWorkerRoute
  LovableEmailEventsRoute: typeof LovableEmailEventsRoute
  ApiPublicEmailInboundRoute: typeof ApiPublicEmailInboundRoute
  ApiPublicOutfitImageSplatRoute: typeof ApiPublicOutfitImageSplatRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$celebration': {
      id: '/$celebration'
      path: '/$celebration'
      fullPath: '/$celebration'
      preLoaderRoute: typeof CelebrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atelier': {
      id: '/_authenticated/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AuthenticatedAtelierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/confirm': {
      id: '/_authenticated/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof AuthenticatedConfirmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery': {
      id: '/_authenticated/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AuthenticatedDeliveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/event': {
      id: '/_authenticated/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof AuthenticatedEventRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guests': {
      id: '/_authenticated/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof AuthenticatedGuestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hosts': {
      id: '/_authenticated/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof AuthenticatedHostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invitation': {
      id: '/_authenticated/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof AuthenticatedInvitationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invite': {
      id: '/_authenticated/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthenticatedInviteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lookbook': {
      id: '/_authenticated/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof AuthenticatedLookbookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/measurements': {
      id: '/_authenticated/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof AuthenticatedMeasurementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outfits': {
      id: '/_authenticated/outfits'
      path: '/outfits'
      fullPath: '/outfits'
      preLoaderRoute: typeof AuthenticatedOutfitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pay': {
      id: '/_authenticated/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof AuthenticatedPayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/summary': {
      id: '/_authenticated/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof AuthenticatedSummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family/$household': {
      id: '/_authenticated/family/$household'
      path: '/family/$household'
      fullPath: '/family/$household'
      preLoaderRoute: typeof AuthenticatedFamilyHouseholdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guest/$guestId': {
      id: '/_authenticated/guest/$guestId'
      path: '/guest/$guestId'
      fullPath: '/guest/$guestId'
      preLoaderRoute: typeof AuthenticatedGuestGuestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guest/invite': {
      id: '/_authenticated/guest/invite'
      path: '/guest/invite'
      fullPath: '/guest/invite'
      preLoaderRoute: typeof AuthenticatedGuestInviteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guest/measurements': {
      id: '/_authenticated/guest/measurements'
      path: '/guest/measurements'
      fullPath: '/guest/measurements'
      preLoaderRoute: typeof AuthenticatedGuestMeasurementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guest/outfits': {
      id: '/_authenticated/guest/outfits'
      path: '/guest/outfits'
      fullPath: '/guest/outfits'
      preLoaderRoute: typeof AuthenticatedGuestOutfitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guest/schedule': {
      id: '/_authenticated/guest/schedule'
      path: '/guest/schedule'
      fullPath: '/guest/schedule'
      preLoaderRoute: typeof AuthenticatedGuestScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guest/summary': {
      id: '/_authenticated/guest/summary'
      path: '/guest/summary'
      fullPath: '/guest/summary'
      preLoaderRoute: typeof AuthenticatedGuestSummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/host/': {
      id: '/_authenticated/host/'
      path: '/host'
      fullPath: '/host/'
      preLoaderRoute: typeof AuthenticatedHostIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/host/$': {
      id: '/_authenticated/host/$'
      path: '/host/$'
      fullPath: '/host/$'
      preLoaderRoute: typeof AuthenticatedHostSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/followup-reminders': {
      id: '/api/public/followup-reminders'
      path: '/api/public/followup-reminders'
      fullPath: '/api/public/followup-reminders'
      preLoaderRoute: typeof ApiPublicFollowupRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/outfit-import-worker': {
      id: '/api/public/outfit-import-worker'
      path: '/api/public/outfit-import-worker'
      fullPath: '/api/public/outfit-import-worker'
      preLoaderRoute: typeof ApiPublicOutfitImportWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/events': {
      id: '/lovable/email/events'
      path: '/lovable/email/events'
      fullPath: '/lovable/email/events'
      preLoaderRoute: typeof LovableEmailEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/inbound': {
      id: '/api/public/email/inbound'
      path: '/api/public/email/inbound'
      fullPath: '/api/public/email/inbound'
      preLoaderRoute: typeof ApiPublicEmailInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/outfit-image/$': {
      id: '/api/public/outfit-image/$'
      path: '/api/public/outfit-image/$'
      fullPath: '/api/public/outfit-image/$'
      preLoaderRoute: typeof ApiPublicOutfitImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtelierRoute: typeof AuthenticatedAtelierRoute
  AuthenticatedConfirmRoute: typeof AuthenticatedConfirmRoute
  AuthenticatedDeliveryRoute: typeof AuthenticatedDeliveryRoute
  AuthenticatedEventRoute: typeof AuthenticatedEventRoute
  AuthenticatedGuestsRoute: typeof AuthenticatedGuestsRoute
  AuthenticatedHostsRoute: typeof AuthenticatedHostsRoute
  AuthenticatedInvitationRoute: typeof AuthenticatedInvitationRoute
  AuthenticatedInviteRoute: typeof AuthenticatedInviteRoute
  AuthenticatedLookbookRoute: typeof AuthenticatedLookbookRoute
  AuthenticatedMeasurementsRoute: typeof AuthenticatedMeasurementsRoute
  AuthenticatedOutfitsRoute: typeof AuthenticatedOutfitsRoute
  AuthenticatedPayRoute: typeof AuthenticatedPayRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSummaryRoute: typeof AuthenticatedSummaryRoute
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
  AuthenticatedFamilyHouseholdRoute: typeof AuthenticatedFamilyHouseholdRoute
  AuthenticatedGuestGuestIdRoute: typeof AuthenticatedGuestGuestIdRoute
  AuthenticatedGuestInviteRoute: typeof AuthenticatedGuestInviteRoute
  AuthenticatedGuestMeasurementsRoute: typeof AuthenticatedGuestMeasurementsRoute
  AuthenticatedGuestOutfitsRoute: typeof AuthenticatedGuestOutfitsRoute
  AuthenticatedGuestScheduleRoute: typeof AuthenticatedGuestScheduleRoute
  AuthenticatedGuestSummaryRoute: typeof AuthenticatedGuestSummaryRoute
  AuthenticatedHostSplatRoute: typeof AuthenticatedHostSplatRoute
  AuthenticatedHostIndexRoute: typeof AuthenticatedHostIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtelierRoute: AuthenticatedAtelierRoute,
  AuthenticatedConfirmRoute: AuthenticatedConfirmRoute,
  AuthenticatedDeliveryRoute: AuthenticatedDeliveryRoute,
  AuthenticatedEventRoute: AuthenticatedEventRoute,
  AuthenticatedGuestsRoute: AuthenticatedGuestsRoute,
  AuthenticatedHostsRoute: AuthenticatedHostsRoute,
  AuthenticatedInvitationRoute: AuthenticatedInvitationRoute,
  AuthenticatedInviteRoute: AuthenticatedInviteRoute,
  AuthenticatedLookbookRoute: AuthenticatedLookbookRoute,
  AuthenticatedMeasurementsRoute: AuthenticatedMeasurementsRoute,
  AuthenticatedOutfitsRoute: AuthenticatedOutfitsRoute,
  AuthenticatedPayRoute: AuthenticatedPayRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSummaryRoute: AuthenticatedSummaryRoute,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
  AuthenticatedFamilyHouseholdRoute: AuthenticatedFamilyHouseholdRoute,
  AuthenticatedGuestGuestIdRoute: AuthenticatedGuestGuestIdRoute,
  AuthenticatedGuestInviteRoute: AuthenticatedGuestInviteRoute,
  AuthenticatedGuestMeasurementsRoute: AuthenticatedGuestMeasurementsRoute,
  AuthenticatedGuestOutfitsRoute: AuthenticatedGuestOutfitsRoute,
  AuthenticatedGuestScheduleRoute: AuthenticatedGuestScheduleRoute,
  AuthenticatedGuestSummaryRoute: AuthenticatedGuestSummaryRoute,
  AuthenticatedHostSplatRoute: AuthenticatedHostSplatRoute,
  AuthenticatedHostIndexRoute: AuthenticatedHostIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CelebrationRoute: CelebrationRoute,
  AuthRoute: AuthRoute,
  ApiPublicFollowupRemindersRoute: ApiPublicFollowupRemindersRoute,
  ApiPublicOutfitImportWorkerRoute: ApiPublicOutfitImportWorkerRoute,
  LovableEmailEventsRoute: LovableEmailEventsRoute,
  ApiPublicEmailInboundRoute: ApiPublicEmailInboundRoute,
  ApiPublicOutfitImageSplatRoute: ApiPublicOutfitImageSplatRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
