/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAtelierRouteImport } from './routes/_authenticated/atelier'
import { Route as AuthenticatedDeliveryRouteImport } from './routes/_authenticated/delivery'
import { Route as AuthenticatedEventRouteImport } from './routes/_authenticated/event'
import { Route as AuthenticatedGuestsRouteImport } from './routes/_authenticated/guests'
import { Route as AuthenticatedHostRouteImport } from './routes/_authenticated/host'
import { Route as AuthenticatedInvitationRouteImport } from './routes/_authenticated/invitation'
import { Route as AuthenticatedLookbookRouteImport } from './routes/_authenticated/lookbook'
import { Route as AuthenticatedMeasurementsRouteImport } from './routes/_authenticated/measurements'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedGuestGuestIdRouteImport } from './routes/_authenticated/guest.$guestId'
import { Route as ApiPublicFollowupRemindersRouteImport } from './routes/api/public/followup-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtelierRoute = AuthenticatedAtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliveryRoute = AuthenticatedDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventRoute = AuthenticatedEventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuestsRoute = AuthenticatedGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHostRoute = AuthenticatedHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitationRoute = AuthenticatedInvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLookbookRoute = AuthenticatedLookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeasurementsRoute =
  AuthenticatedMeasurementsRouteImport.update({
    id: '/measurements',
    path: '/measurements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuestGuestIdRoute =
  AuthenticatedGuestGuestIdRouteImport.update({
    id: '/guest/$guestId',
    path: '/guest/$guestId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicFollowupRemindersRoute =
  ApiPublicFollowupRemindersRouteImport.update({
    id: '/api/public/followup-reminders',
    path: '/api/public/followup-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/atelier': typeof AuthenticatedAtelierRoute
  '/delivery': typeof AuthenticatedDeliveryRoute
  '/event': typeof AuthenticatedEventRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/host': typeof AuthenticatedHostRoute
  '/invitation': typeof AuthenticatedInvitationRoute
  '/lookbook': typeof AuthenticatedLookbookRoute
  '/measurements': typeof AuthenticatedMeasurementsRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/guest/$guestId': typeof AuthenticatedGuestGuestIdRoute
  '/api/public/followup-reminders': typeof ApiPublicFollowupRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/atelier': typeof AuthenticatedAtelierRoute
  '/delivery': typeof AuthenticatedDeliveryRoute
  '/event': typeof AuthenticatedEventRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/host': typeof AuthenticatedHostRoute
  '/invitation': typeof AuthenticatedInvitationRoute
  '/lookbook': typeof AuthenticatedLookbookRoute
  '/measurements': typeof AuthenticatedMeasurementsRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/guest/$guestId': typeof AuthenticatedGuestGuestIdRoute
  '/api/public/followup-reminders': typeof ApiPublicFollowupRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/atelier': typeof AuthenticatedAtelierRoute
  '/_authenticated/delivery': typeof AuthenticatedDeliveryRoute
  '/_authenticated/event': typeof AuthenticatedEventRoute
  '/_authenticated/guests': typeof AuthenticatedGuestsRoute
  '/_authenticated/host': typeof AuthenticatedHostRoute
  '/_authenticated/invitation': typeof AuthenticatedInvitationRoute
  '/_authenticated/lookbook': typeof AuthenticatedLookbookRoute
  '/_authenticated/measurements': typeof AuthenticatedMeasurementsRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRoute
  '/_authenticated/guest/$guestId': typeof AuthenticatedGuestGuestIdRoute
  '/api/public/followup-reminders': typeof ApiPublicFollowupRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/atelier'
    | '/delivery'
    | '/event'
    | '/guests'
    | '/host'
    | '/invitation'
    | '/lookbook'
    | '/measurements'
    | '/plan'
    | '/platform'
    | '/guest/$guestId'
    | '/api/public/followup-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/atelier'
    | '/delivery'
    | '/event'
    | '/guests'
    | '/host'
    | '/invitation'
    | '/lookbook'
    | '/measurements'
    | '/plan'
    | '/platform'
    | '/guest/$guestId'
    | '/api/public/followup-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/atelier'
    | '/_authenticated/delivery'
    | '/_authenticated/event'
    | '/_authenticated/guests'
    | '/_authenticated/host'
    | '/_authenticated/invitation'
    | '/_authenticated/lookbook'
    | '/_authenticated/measurements'
    | '/_authenticated/plan'
    | '/_authenticated/platform'
    | '/_authenticated/guest/$guestId'
    | '/api/public/followup-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicFollowupRemindersRoute: typeof ApiPublicFollowupRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atelier': {
      id: '/_authenticated/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AuthenticatedAtelierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery': {
      id: '/_authenticated/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AuthenticatedDeliveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/event': {
      id: '/_authenticated/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof AuthenticatedEventRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guests': {
      id: '/_authenticated/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof AuthenticatedGuestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/host': {
      id: '/_authenticated/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof AuthenticatedHostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invitation': {
      id: '/_authenticated/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof AuthenticatedInvitationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lookbook': {
      id: '/_authenticated/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof AuthenticatedLookbookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/measurements': {
      id: '/_authenticated/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof AuthenticatedMeasurementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guest/$guestId': {
      id: '/_authenticated/guest/$guestId'
      path: '/guest/$guestId'
      fullPath: '/guest/$guestId'
      preLoaderRoute: typeof AuthenticatedGuestGuestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/followup-reminders': {
      id: '/api/public/followup-reminders'
      path: '/api/public/followup-reminders'
      fullPath: '/api/public/followup-reminders'
      preLoaderRoute: typeof ApiPublicFollowupRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtelierRoute: typeof AuthenticatedAtelierRoute
  AuthenticatedDeliveryRoute: typeof AuthenticatedDeliveryRoute
  AuthenticatedEventRoute: typeof AuthenticatedEventRoute
  AuthenticatedGuestsRoute: typeof AuthenticatedGuestsRoute
  AuthenticatedHostRoute: typeof AuthenticatedHostRoute
  AuthenticatedInvitationRoute: typeof AuthenticatedInvitationRoute
  AuthenticatedLookbookRoute: typeof AuthenticatedLookbookRoute
  AuthenticatedMeasurementsRoute: typeof AuthenticatedMeasurementsRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRoute
  AuthenticatedGuestGuestIdRoute: typeof AuthenticatedGuestGuestIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtelierRoute: AuthenticatedAtelierRoute,
  AuthenticatedDeliveryRoute: AuthenticatedDeliveryRoute,
  AuthenticatedEventRoute: AuthenticatedEventRoute,
  AuthenticatedGuestsRoute: AuthenticatedGuestsRoute,
  AuthenticatedHostRoute: AuthenticatedHostRoute,
  AuthenticatedInvitationRoute: AuthenticatedInvitationRoute,
  AuthenticatedLookbookRoute: AuthenticatedLookbookRoute,
  AuthenticatedMeasurementsRoute: AuthenticatedMeasurementsRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRoute,
  AuthenticatedGuestGuestIdRoute: AuthenticatedGuestGuestIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicFollowupRemindersRoute: ApiPublicFollowupRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
